/**
 * Module ID: 600
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 600);
const m = module;
const _e = exports;
const d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";function e(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(_e,'__esModule',{value:!0}),Object.defineProperty(_e,"AntDesign",{enumerable:!0,get:function(){return t.default}}),Object.defineProperty(_e,"Entypo",{enumerable:!0,get:function(){return n.default}}),Object.defineProperty(_e,"EvilIcons",{enumerable:!0,get:function(){return u.default}}),Object.defineProperty(_e,"Feather",{enumerable:!0,get:function(){return o.default}}),Object.defineProperty(_e,"Fontisto",{enumerable:!0,get:function(){return f.default}}),Object.defineProperty(_e,"FontAwesome",{enumerable:!0,get:function(){return c.default}}),Object.defineProperty(_e,"FontAwesome5",{enumerable:!0,get:function(){return l.default}}),Object.defineProperty(_e,"FontAwesome6",{enumerable:!0,get:function(){return b.default}}),Object.defineProperty(_e,"Foundation",{enumerable:!0,get:function(){return y.default}}),Object.defineProperty(_e,"Ionicons",{enumerable:!0,get:function(){return p.default}}),Object.defineProperty(_e,"MaterialCommunityIcons",{enumerable:!0,get:function(){return O.default}}),Object.defineProperty(_e,"MaterialIcons",{enumerable:!0,get:function(){return j.default}}),Object.defineProperty(_e,"Octicons",{enumerable:!0,get:function(){return P.default}}),Object.defineProperty(_e,"SimpleLineIcons",{enumerable:!0,get:function(){return s.default}}),Object.defineProperty(_e,"Zocial",{enumerable:!0,get:function(){return I.default}}),Object.defineProperty(_e,"createMultiStyleIconSet",{enumerable:!0,get:function(){return F.default}}),Object.defineProperty(_e,"createIconSet",{enumerable:!0,get:function(){return M.default}}),Object.defineProperty(_e,"createIconSetFromFontello",{enumerable:!0,get:function(){return S.default}}),Object.defineProperty(_e,"createIconSetFromIcoMoon",{enumerable:!0,get:function(){return _.default}});var t=e(require("./default_601")),n=e(require("./default_633")),u=e(require("./default_636")),o=e(require("./default_639")),f=e(require("./default_642")),c=e(require("./default_645")),l=e(require("./default_648")),b=e(require("./default_656")),y=e(require("./default_663")),p=e(require("./default_666")),O=e(require("./default_669")),j=e(require("./default_672")),P=e(require("./default_675")),s=e(require("./default_678")),I=e(require("./default_681")),F=e(require("./default_650")),M=e(require("./DEFAULT_ICON_COLOR_602")),S=e(require("./default_684")),_=e(require("./default_686"))