/**
 * Module ID: 312
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 312);
const m = module;
const _e = exports;
const d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

'use strict';Object.defineProperty(_e,'__esModule',{value:!0}),Object.defineProperty(_e,"default",{enumerable:!0,get:function(){return o}});var t,e=require("./default_22"),s=(t=e)&&t.__esModule?t:{default:t};class n{constructor(){this.any_blank_count=0,this.any_blank_ms=0,this.any_blank_speed_sum=0,this.mostly_blank_count=0,this.mostly_blank_ms=0,this.pixels_blank=0,this.pixels_sampled=0,this.pixels_scrolled=0,this.total_time_spent=0,this.sample_count=0}}var l=[],_=10,h=null;var o=class{static addListener(t){return null===h&&console.warn('Call `FillRateHelper.setSampleRate` before `addListener`.'),l.push(t),{remove:()=>{l=l.filter(e=>t!==e)}}}static setSampleRate(t){h=t}static setMinSampleCount(t){_=t}constructor(t){this._anyBlankStartTime=null,this._enabled=!1,this._info=new n,this._mostlyBlankStartTime=null,this._samplesStartTime=null,this._getFrameMetrics=t,this._enabled=(h||0)>Math.random(),this._resetData()}activate(){this._enabled&&null==this._samplesStartTime&&(this._samplesStartTime=g.performance.now())}deactivateAndFlush(){if(this._enabled){var t=this._samplesStartTime;if(null!=t)if(this._info.sample_count<_)this._resetData();else{var e=g.performance.now()-t,n=(0,s.default)((0,s.default)({},this._info),{},{total_time_spent:e});l.forEach(t=>t(n)),this._resetData()}}}computeBlankness(t,e,s){if(!this._enabled||0===t.getItemCount(t.data)||e.last<e.first||null==this._samplesStartTime)return 0;var n=s.dOffset,l=s.offset,_=s.velocity,h=s.visibleLength;this._info.sample_count++,this._info.pixels_sampled+=Math.round(h),this._info.pixels_scrolled+=Math.round(Math.abs(n));var o=Math.round(1e3*Math.abs(_)),u=g.performance.now();null!=this._anyBlankStartTime&&(this._info.any_blank_ms+=u-this._anyBlankStartTime),this._anyBlankStartTime=null,null!=this._mostlyBlankStartTime&&(this._info.mostly_blank_ms+=u-this._mostlyBlankStartTime),this._mostlyBlankStartTime=null;for(var f=0,c=e.first,p=this._getFrameMetrics(c,t);c<=e.last&&(!p||!p.inLayout);)p=this._getFrameMetrics(c,t),c++;p&&c>0&&(f=Math.min(h,Math.max(0,p.offset-l)));for(var b=0,y=e.last,k=this._getFrameMetrics(y,t);y>=e.first&&(!k||!k.inLayout);)k=this._getFrameMetrics(y,t),y--;if(k&&y<t.getItemCount(t.data)-1){var S=k.offset+k.length;b=Math.min(h,Math.max(0,l+h-S))}var M=Math.round(f+b),v=M/h;return v>0?(this._anyBlankStartTime=u,this._info.any_blank_speed_sum+=o,this._info.any_blank_count++,this._info.pixels_blank+=M,v>.5&&(this._mostlyBlankStartTime=u,this._info.mostly_blank_count++)):(o<.01||Math.abs(n)<1)&&this.deactivateAndFlush(),v}enabled(){return this._enabled}_resetData(){this._anyBlankStartTime=null,this._info=new n,this._mostlyBlankStartTime=null,this._samplesStartTime=null}}