/**
 * Module ID: 1012
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 1012);
const m = module;
const _e = exports;
const d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";Object.defineProperty(_e,'__esModule',{value:!0}),Object.defineProperty(_e,"default",{enumerable:!0,get:function(){return c}}),_e.props2transform=o,_e.transformToMatrix=u,_e.extractTransformSvgView=function(e){if('string'==typeof e.transform)return(0,t.parse)(e.transform);return e.transform},_e.stringifyTransformArrayProps=y;var e=require("./module_1013"),n=require("./module_1014"),t=require("./module_1015");function s(n){const{x:t,y:s,originX:l,originY:o,scaleX:u,scaleY:c,rotation:f,skewX:y,skewY:p}=n;(0,e.appendTransform)(t+l,s+o,u,c,f,y,p,l,o)}function l(e,n,t,s){let l,o;if('number'==typeof e)l=o=e;else if('string'==typeof e){const n=e.split(/\s*,\s*/);2===n.length?(l=+n[0],o=+n[1]):1===n.length&&(l=o=+n[0])}else Array.isArray(e)&&(2===e.length?(l=+e[0],o=+e[1]):1===e.length&&(l=o=+e[0]));return n=+n,isNaN(n)||(l=n),t=+t,isNaN(t)||(o=t),[l||s||0,o||s||0]}function o(e){if(!e)return null;const{rotation:n,translate:t,translateX:s,translateY:o,origin:u,originX:c,originY:f,scale:y,scaleX:p,scaleY:A,skew:w,skewX:X,skewY:Y,x:h,y:k}=e;if(null==n&&null==t&&null==s&&null==o&&null==u&&null==c&&null==f&&null==y&&null==p&&null==A&&null==w&&null==X&&null==Y&&null==h&&null==k)return null;(Array.isArray(h)||Array.isArray(k))&&console.warn('Passing SvgLengthList to x or y attribute where SvgLength expected');const x=l(t,s||(Array.isArray(h)?h[0]:h),o||(Array.isArray(k)?k[0]:k)),$=l(u,c,f),b=l(y,p,A,1),v=l(w,X,Y);return{rotation:null==n?0:+n||0,originX:$[0],originY:$[1],scaleX:b[0],scaleY:b[1],skewX:v[0],skewY:v[1],x:x[0],y:x[1]}}function u(t,l){if(!t&&!l)return null;if((0,e.reset)(),t&&s(t),l)if(Array.isArray(l))if('number'==typeof l[0]){const n=l;(0,e.append)(n[0],n[1],n[2],n[3],n[4],n[5])}else{const t=y(l),s=(0,n.parse)(t);(0,e.append)(s[0],s[3],s[1],s[4],s[2],s[5])}else if('string'==typeof l)try{const t=(0,n.parse)(l);(0,e.append)(t[0],t[3],t[1],t[4],t[2],t[5])}catch(e){console.error(e)}else{const e=o(l);e&&s(e)}return(0,e.toArray)()}function c(t){if(Array.isArray(t)&&'number'==typeof t[0])return t;if('string'==typeof t)try{const e=(0,n.parse)(t);return[e[0],e[3],e[1],e[4],e[2],e[5]]}catch(n){return console.error(n),e.identity}const s=t;return u(o(s),null==s?void 0:s.transform)}const f=e=>e.endsWith('rad')?parseFloat(e)*(180/Math.PI):e.endsWith('deg')?parseFloat(e):void 0;function y(e){return e?e.map(e=>{const[n,t]=Object.entries(e)[0];switch(n){case'translateX':return`translate(${t}, 0)`;case'translateY':return`translate(0, ${t})`;case'rotate':return`rotate(${f(t)})`;case'scale':return`scale(${t})`;case'scaleX':return`scale(${t}, 1)`;case'scaleY':return`scale(1, ${t})`;case'skewX':return`skewX(${f(t)})`;case'skewY':return`skewY(${f(t)})`;case'matrix':return`matrix(${t.join(', ')})`;default:return''}}).join(' '):''}