/**
 * Module ID: 314
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 314);
const m = module;
const _e = exports;
const d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

'use strict';function e(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(_e,'__esModule',{value:!0}),Object.defineProperty(_e,"default",{enumerable:!0,get:function(){return u}});var t=e(require("./default_22")),n=e(require("./default_293")),s=e(require("./module_27"));function l(e,t,n,s,l,u){if(h(n,s,l))return!0;var c=o(n,s,l);return 100*(e?c/l:c/u)>=t}function o(e,t,n){var s=Math.min(t,n)-Math.max(e,0);return Math.max(0,s)}function h(e,t,n){return e>=0&&t<=n&&t>e}var u=class{constructor(e){void 0===e&&(e={viewAreaCoveragePercentThreshold:0}),this._hasInteracted=!1,this._timers=new Set,this._viewableIndices=[],this._viewableItems=new Map,this._config=e}dispose(){this._timers.forEach(clearTimeout)}computeViewableItems(e,t,n,o,h){var u=e.getItemCount(e.data),c=this._config,f=c.itemVisiblePercentThreshold,v=c.viewAreaCoveragePercentThreshold,_=null!=v,w=_?v:f;(0,s.default)(null!=w&&null!=f!=(null!=v),'Must set exactly one of itemVisiblePercentThreshold or viewAreaCoveragePercentThreshold');var b=[];if(0===u)return b;var I=-1,p=h||{first:0,last:u-1},y=p.first,T=p.last;if(T>=u)return console.warn('Invalid render range computing viewability '+JSON.stringify({renderRange:h,itemCount:u})),[];for(var M=y;M<=T;M++){var V=o(M,e);if(V){var C=V.offset-t,P=C+V.length;if(C<n&&P>0)I=M,l(_,w,C,P,n,V.length)&&b.push(M);else if(I>=0)break}}return b}onUpdate(e,t,n,s,l,o,h){var u=e.getItemCount(e.data);if((!this._config.waitForInteraction||this._hasInteracted)&&0!==u&&s(0,e)){var c=[];if(u&&(c=this.computeViewableItems(e,t,n,s,h)),this._viewableIndices.length!==c.length||!this._viewableIndices.every((e,t)=>e===c[t]))if(this._viewableIndices=c,this._config.minimumViewTime){var f=setTimeout(()=>{this._timers.delete(f),this._onUpdateSync(e,c,o,l)},this._config.minimumViewTime);this._timers.add(f)}else this._onUpdateSync(e,c,o,l)}}resetViewableIndices(){this._viewableIndices=[]}recordInteraction(){this._hasInteracted=!0}_onUpdateSync(e,s,l,o){s=s.filter(e=>this._viewableIndices.includes(e));for(var h,u=this._viewableItems,c=new Map(s.map(t=>{var n=o(t,!0,e);return[n.key,n]})),f=[],v=(0,n.default)(c);!(h=v()).done;){var _=h.value,w=_[0],b=_[1];u.has(w)||f.push(b)}for(var I,p=(0,n.default)(u);!(I=p()).done;){var y=I.value,T=y[0],M=y[1];c.has(T)||f.push((0,t.default)((0,t.default)({},M),{},{isViewable:!1}))}f.length>0&&(this._viewableItems=c,l({viewableItems:Array.from(c.values()),changed:f,viewabilityConfig:this._config}))}}