/**
 * Module ID: 143
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 143);
const m = module;
const _e = exports;
const d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";function e(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(_e,'__esModule',{value:!0}),Object.defineProperty(_e,"default",{enumerable:!0,get:function(){return F}});var t=require("./module_37"),n=e(require("./default_144")),o=e(require("./default_45")),s=require("./JP_useScoreStore_174"),c=require("./JP_MainNavigator_216"),l=require("./JP_LoginScreen_1036"),u=require("./JP_LoadingScreen_1037"),h=require("./module_420"),f=require("./module_1038"),p=require("./JP_ErrorBoundary_1041"),b=require("./JP_OfflineIndicator_1042"),S=require("./IS_WEB_199"),x=require("./module_427");function F(){const e=(0,s.useScoreStore)(e=>e.isHydrated),o=(0,s.useScoreStore)(e=>e.activeGroupId),F=(0,s.useScoreStore)(e=>e.startPeriodicSync),w=(0,s.useScoreStore)(e=>e.fetchAndOverwriteFromCloud),C=(0,s.useScoreStore)(e=>e.setupNetworkListener),[j,v]=(0,t.useState)(!1);return(0,t.useEffect)(()=>{v(!0);const e=C();return()=>e()},[]),(0,t.useEffect)(()=>{if(e&&o){console.log('[App] Initializing data for group:',o);try{w(),F()}catch(e){console.error('[App] Initial data fetch error:',e)}}else console.log('[App] Waiting for:',{isHydrated:e,activeGroupId:o})},[e,o]),console.log(`[App] Rendering. hasMounted: ${j}, isHydrated: ${e}, activeGroupId: ${o}`),j&&e?(0,x.jsxs)(n.default,{style:y.appContainer,children:[S.IS_WEB&&(0,x.jsx)("style",{dangerouslySetInnerHTML:{__html:"\n          ::-webkit-scrollbar {\n            width: 8px;\n            height: 8px;\n          }\n          ::-webkit-scrollbar-track {\n            background: #F2F2F7;\n          }\n          ::-webkit-scrollbar-thumb {\n            background: #C7C7CC;\n            border-radius: 4px;\n          }\n          ::-webkit-scrollbar-thumb:hover {\n            background: #8E8E93;\n          }\n          * {\n            scrollbar-width: thin;\n            scrollbar-color: #C7C7CC #F2F2F7;\n          }\n        "}}),(0,x.jsx)(n.default,{style:y.responsiveWrapper,children:(0,x.jsx)(h.SafeAreaProvider,{style:{flex:1,width:'100%',height:'100%'},children:(0,x.jsxs)(p.ErrorBoundary,{children:[(0,x.jsx)(f.StatusBar,{style:"dark"}),o?(0,x.jsxs)(x.Fragment,{children:[(0,x.jsx)(c.MainNavigator,{}),(0,x.jsx)(b.OfflineIndicator,{})]}):(0,x.jsx)(l.LoginScreen,{})]})})})]}):(0,x.jsx)(u.LoadingScreen,{})}const y=o.default.create({appContainer:{flex:1,backgroundColor:'#F2F2F7',alignItems:'center',justifyContent:'center'},responsiveWrapper:{flex:1,width:'100%',maxWidth:S.IS_WEB?1e3:void 0,backgroundColor:'#FFFFFF',shadowColor:'#000',shadowOffset:{width:0,height:4},shadowOpacity:S.IS_WEB?.1:0,shadowRadius:12,elevation:5}})