/**
 * Module ID: 214
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const _r = require;
const _i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 214);
const m = module;
const _e = exports;
const _d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";function t(t){return t&&t.__esModule?t:{default:t}}Object.defineProperty(_e,'__esModule',{value:!0}),Object.defineProperty(_e,"default",{enumerable:!0,get:function(){return h}});var e=t(require("./default_210")),i=t(require("./default_215")),n=(function(t){if(t&&t.__esModule)return t;var e={};return t&&Object.keys(t).forEach(function(i){var n=Object.getOwnPropertyDescriptor(t,i);Object.defineProperty(e,i,n.get?n:{enumerable:!0,get:function(){return t[i]}})}),e.default=t,e})(require("./module_212"));function r(t,e,i){var n;return(e="symbol"==typeof(n=s(e,"string"))?n:String(n))in t?Object.defineProperty(t,e,{value:i,enumerable:!0,configurable:!0,writable:!0}):t[e]=i,t}function s(t,e){if("object"!=typeof t||!t)return t;var i=t[Symbol.toPrimitive];if(void 0!==i){var n=i.call(t,e||"default");if("object"!=typeof n)return n;throw new TypeError("@@toPrimitive must return a primitive value.")}return("string"===e?String:Number)(t)}class h{constructor(t){r(this,"_nativeEventSubscription",null),r(this,"_subscriptions",new Set),r(this,"_latestState",null),r(this,"_internetReachability",void 0),r(this,"_handleNativeStateUpdate",t=>{this._internetReachability.update(t);const e=this._convertState(t);this._latestState=e,this._subscriptions.forEach(t=>t(e))}),r(this,"_handleInternetReachabilityUpdate",t=>{if(!this._latestState)return;const e=Object.assign({},this._latestState,{isInternetReachable:t});this._latestState=e,this._subscriptions.forEach(t=>t(e))}),r(this,"_fetchCurrentState",async t=>{const i=await e.default.getCurrentState(t);this._internetReachability.update(i);const n=this._convertState(i);return t||(this._latestState=n,this._subscriptions.forEach(t=>t(n))),n}),r(this,"_convertState",t=>'boolean'==typeof t.isInternetReachable?t:Object.assign({},t,{isInternetReachable:this._internetReachability.currentState()})),r(this,"latest",t=>t?this._fetchCurrentState(t):this._latestState?Promise.resolve(this._latestState):this._fetchCurrentState()),r(this,"add",t=>{this._subscriptions.add(t),this._latestState?t(this._latestState):this.latest().then(t)}),r(this,"remove",t=>{this._subscriptions.delete(t)}),r(this,"tearDown",()=>{this._internetReachability&&this._internetReachability.tearDown(),this._nativeEventSubscription&&this._nativeEventSubscription.remove(),this._subscriptions.clear()}),this._internetReachability=new i.default(t,this._handleInternetReachabilityUpdate),this._nativeEventSubscription=e.default.eventEmitter.addListener(n.DEVICE_CONNECTIVITY_EVENT,this._handleNativeStateUpdate),this._fetchCurrentState()}}