/**
 * Module ID: 626
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 626);
const m = module;
const _e = exports;
const d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";const e=["name","size","color","style","children"];function t(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(_e,'__esModule',{value:!0}),Object.defineProperty(_e,"default",{enumerable:!0,get:function(){return F}}),Object.defineProperty(_e,"NativeIconAPI",{enumerable:!0,get:function(){return h}}),Object.defineProperty(_e,"DEFAULT_ICON_SIZE",{enumerable:!0,get:function(){return I}}),Object.defineProperty(_e,"DEFAULT_ICON_COLOR",{enumerable:!0,get:function(){return O}});var n=t(require("./module_130")),o=require("./module_37");require("./module_98");var c=t(require("./default_342")),u=t(require("./default_53")),l=t(require("./default_217")),s=t(require("./default_284")),f=t(require("./default_627")),y=t(require("./module_628")),p=t(require("./default_629")),b=require("./module_427");const h=s.default.RNVectorIconsManager||s.default.RNVectorIconsModule,I=12,O='black';function F(t,s,F,P){const S=F?F.replace(/\.(otf|ttf)$/,''):s;class _ extends o.PureComponent{root=null;static defaultProps={size:I,allowFontScaling:!1};render(){const o=this.props,{name:c,size:u,color:s,style:f,children:y}=o,p=(0,n.default)(o,e);let h=c?t[c]||'?':'';'number'==typeof h&&(h=String.fromCodePoint(h));const I={fontSize:u,color:s},O={fontFamily:S,fontWeight:'normal',fontStyle:'normal'};return p.style=[I,f,O,P||{}],(0,b.jsxs)(l.default,Object.assign({selectable:!1},p,{children:[h,y]}))}}const j=(0,y.default)();function $(e){const n=t[e]||'?';return'number'==typeof n?String.fromCodePoint(n):n}return _.Button=(0,p.default)(_),_.getImageSource=async function(e,t=I,n=O){(0,f.default)();const o=$(e),l=(0,u.default)(n),s=`${o}:${t}:${l}`;if(j.has(s))return j.get(s);try{const e={uri:await h.getImageForFont(S,o,t,l),scale:c.default.get()};return j.setValue(s,e),e}catch(e){throw j.setError(s,e),e}},_.getImageSourceSync=function(e,t=I,n=O){(0,f.default)();const o=$(e),l=(0,u.default)(n),s=`${o}:${t}:${l}`;if(j.has(s))return j.get(s);try{const e={uri:h.getImageForFontSync(S,o,t,l),scale:c.default.get()};return j.setValue(s,e),e}catch(e){throw j.setError(s,e),e}},_.loadFont=async function(e=F){},_.hasIcon=function(e){return Object.prototype.hasOwnProperty.call(t,e)},_.getRawGlyphMap=function(){return t},_.getFontFamily=function(){return S},_}