/**
 * Module ID: 325
 */
"use strict";

const _g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const _r = require;
const _i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const _a = (typeof id !== 'undefined' ? id : 325);
const m = module;
const _e = exports;
const d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

'use strict';function t(t){return t&&t.__esModule?t:{default:t}}Object.defineProperty(_e,'__esModule',{value:!0}),Object.defineProperty(_e,"default",{enumerable:!0,get:function(){return g}});var e=t(require("./default_22")),a=t(require("./default_326")),n=t(require("./default_328")),r=t(require("./module_27")),i=t(require("./module_54")),o=t=>t;function u(t){if(t.outputRange&&'string'==typeof t.outputRange[0])return _(t);var e=t.outputRange,a=t.inputRange,n=t.easing||o,i='extend';void 0!==t.extrapolateLeft?i=t.extrapolateLeft:void 0!==t.extrapolate&&(i=t.extrapolate);var u='extend';return void 0!==t.extrapolateRight?u=t.extrapolateRight:void 0!==t.extrapolate&&(u=t.extrapolate),t=>{(0,r.default)('number'==typeof t,'Cannot interpolation an input which is not a number');var o=s(t,a);return p(t,a[o],a[o+1],e[o],e[o+1],n,i,u)}}function p(t,e,a,n,r,i,o,u){var p=t;if(p<e){if('identity'===o)return p;'clamp'===o&&(p=e)}if(p>a){if('identity'===u)return p;'clamp'===u&&(p=a)}return n===r?n:e===a?t<=e?n:r:(e===-1/0?p=-p:a===1/0?p-=e:p=(p-e)/(a-e),p=i(p),n===-1/0?p=-p:r===1/0?p+=n:p=p*(r-n)+n,p)}function l(t){var e=(0,i.default)(t);return null===e||'number'!=typeof e?t:"rgba("+((4278190080&(e=e||0))>>>24)+", "+((16711680&e)>>>16)+", "+((65280&e)>>>8)+", "+(255&e)/255+")"}var f=/[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?/g;function _(t){var a=t.outputRange;(0,r.default)(a.length>=2,'Bad output range'),h(a=a.map(l));var n=a[0].match(f).map(()=>[]);a.forEach(t=>{t.match(f).forEach((t,e)=>{n[e].push(+t)})});var i,o=a[0].match(f).map((a,r)=>u((0,e.default)((0,e.default)({},t),{},{outputRange:n[r]}))),p='string'==typeof(i=a[0])&&i.startsWith('rgb');return t=>{var e=0;return a[0].replace(f,()=>{var a=+o[e++](t);return p&&(a=e<4?Math.round(a):Math.round(1e3*a)/1e3),String(a)})}}function h(t){for(var e=t[0].replace(f,''),a=1;a<t.length;++a)(0,r.default)(e===t[a].replace(f,''),'invalid pattern '+t[0]+' and '+t[a])}function s(t,e){var a;for(a=1;a<e.length-1&&!(e[a]>=t);++a);return a-1}class c extends a.default{constructor(t,e){super(),this._parent=t,this._config=e,this._interpolation=u(e)}__makeNative(t){this._parent.__makeNative(t),super.__makeNative(t)}__getValue(){var t=this._parent.__getValue();return(0,r.default)('number'==typeof t,'Cannot interpolate an input which is not a number.'),this._interpolation(t)}interpolate(t){return new c(this,t)}__attach(){this._parent.__addChild(this)}__detach(){this._parent.__removeChild(this),super.__detach()}__transformDataType(t){return t.map(n.default.transformDataType)}__getNativeConfig(){return{inputRange:this._config.inputRange,outputRange:this.__transformDataType(this._config.outputRange),extrapolateLeft:this._config.extrapolateLeft||this._config.extrapolate||'extend',extrapolateRight:this._config.extrapolateRight||this._config.extrapolate||'extend',type:'interpolation'}}}c.__createInterpolation=u;var g=c