/**
 * Module ID: 315
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 315);
const m = module;
const _e = exports;
const _d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";function e(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(_e,'__esModule',{value:!0}),Object.defineProperty(_e,"default",{enumerable:!0,get:function(){return d}});var t=e(require("./default_30")),o=e(require("./default_22")),s=e(require("./default_144")),n=e(require("./default_45")),l=require("./VirtualizedListContext_316"),p=e(require("./module_27")),u=(function(e){if(e&&e.__esModule)return e;var t={};return e&&Object.keys(e).forEach(function(o){var s=Object.getOwnPropertyDescriptor(e,o);Object.defineProperty(t,o,s.get?s:{enumerable:!0,get:function(){return e[o]}})}),t.default=e,t})(require("./module_37"));class d extends u.Component{constructor(){super(...arguments),this.state={separatorProps:{highlighted:!1,leadingItem:this.props.item}},this._separators={highlight:()=>{var e=this.props,t=e.cellKey,o=e.prevCellKey;this.props.onUpdateSeparators([t,o],{highlighted:!0})},unhighlight:()=>{var e=this.props,t=e.cellKey,o=e.prevCellKey;this.props.onUpdateSeparators([t,o],{highlighted:!1})},updateProps:(e,t)=>{var o=this.props,s=o.cellKey,n=o.prevCellKey;this.props.onUpdateSeparators(['leading'===e?n:s],t)}},this._onLayout=e=>{this.props.onCellLayout&&this.props.onCellLayout(e,this.props.cellKey,this.props.index)}}static getDerivedStateFromProps(e,t){return{separatorProps:(0,o.default)((0,o.default)({},t.separatorProps),{},{leadingItem:e.item})}}updateSeparatorProps(e){this.setState(t=>({separatorProps:(0,o.default)((0,o.default)({},t.separatorProps),e)}))}componentWillUnmount(){this.props.onUnmount(this.props.cellKey)}_renderElement(e,t,o,s){return e&&t&&console.warn("VirtualizedList: Both ListItemComponent and renderItem props are present. ListItemComponent will take precedence over renderItem."),t?u.createElement(t,{item:o,index:s,separators:this._separators}):e?e({item:o,index:s,separators:this._separators}):void(0,p.default)(!1,'VirtualizedList: Either ListItemComponent or renderItem props are required but none were found.')}render(){var e=this.props,o=e.CellRendererComponent,n=e.ItemSeparatorComponent,p=e.ListItemComponent,d=e.cellKey,h=e.horizontal,y=e.item,f=e.index,v=e.inversionStyle,C=e.onCellFocusCapture,_=e.onCellLayout,L=e.renderItem,P=this._renderElement(L,p,y,f),K=u.isValidElement(n)?n:n&&u.createElement(n,this.state.separatorProps),I=v?h?[c.rowReverse,v]:[c.columnReverse,v]:h?[c.row,v]:v,w=o?u.createElement(o,(0,t.default)({cellKey:d,index:f,item:y,style:I,onFocusCapture:C},_&&{onLayout:this._onLayout}),P,K):u.createElement(s.default,(0,t.default)({style:I,onFocusCapture:C},_&&{onLayout:this._onLayout}),P,K);return u.createElement(l.VirtualizedListCellContextProvider,{cellKey:this.props.cellKey},w)}}var c=n.default.create({row:{flexDirection:'row'},rowReverse:{flexDirection:'row-reverse'},columnReverse:{flexDirection:'column-reverse'}})