/**
 * Module ID: 604
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 604);
const m = module;
const _e = exports;
const d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";Object.defineProperty(_e,'__esModule',{value:!0}),_e.isLoaded=c,_e.getLoadedFonts=function(){return t.default.getLoadedFonts()},_e.isLoading=function(e){return e in u.loadPromises},_e.loadAsync=function(e,n){const t='undefined'==typeof window;if('object'==typeof e){if(n)return Promise.reject(new o.CodedError("ERR_FONT_API",`No fontFamily can be used for the provided source: ${n}. The second argument of \`loadAsync()\` can only be used with a \`string\` value as the first argument.`));const s=e,l=Object.keys(s);return t?(l.map(e=>(0,f.registerStaticFont)(e,s[e])),Promise.resolve()):Promise.all(l.map(e=>y(e,s[e]))).then(()=>{})}if(t)return(0,f.registerStaticFont)(e,n),Promise.resolve();return y(e,n)},_e.unloadAllAsync=async function(){if(!t.default.unloadAllAsync)throw new o.UnavailabilityError('expo-font','unloadAllAsync');if(Object.keys(u.loadPromises).length)throw new o.CodedError("ERR_UNLOAD",`Cannot unload fonts while they're still loading: ${Object.keys(u.loadPromises).join(', ')}`);(0,u.purgeCache)(),await t.default.unloadAllAsync()},_e.unloadAsync=async function(e,n){if(!t.default.unloadAsync)throw new o.UnavailabilityError('expo-font','unloadAsync');if('object'==typeof e){if(n)throw new o.CodedError("ERR_FONT_API",`No fontFamily can be used for the provided options: ${n}. The second argument of \`unloadAsync()\` can only be used with a \`string\` value as the first argument.`);const t=e,s=Object.keys(t);return void await Promise.all(s.map(e=>w(e,t[e])))}return await w(e,n)},Object.defineProperty(_e,"FontDisplay",{enumerable:!0,get:function(){return s.FontDisplay}});var e,o=require("./EventEmitter_100"),n=require("./default_605"),t=(e=n)&&e.__esModule?e:{default:e},s=require("./module_607"),l=require("./module_608"),u=require("./loadPromises_621"),f=require("./module_622");function c(e){if('function'!=typeof t.default.isLoaded)throw new Error("expected ExpoFontLoader.isLoaded to be a function, was "+typeof t.default.isLoaded);return(0,u.isLoadedInCache)(e)||t.default.isLoaded(e)}async function y(e,n){if(!n)throw new o.CodedError("ERR_FONT_SOURCE",`Cannot load null or undefined font source: { "${e}": ${n} }. Expected asset of type \`FontSource\` for fontFamily of name: "${e}"`);if(c(e))return;if(u.loadPromises.hasOwnProperty(e))return u.loadPromises[e];const t=(0,l.getAssetForSource)(n);u.loadPromises[e]=(async()=>{try{await(0,l.loadSingleFontAsync)(e,t),(0,u.markLoaded)(e)}finally{delete u.loadPromises[e]}})(),await u.loadPromises[e]}async function w(e,n){if(c(e)){if((0,u.purgeFontFamilyFromCache)(e),!e)throw new o.CodedError("ERR_FONT_FAMILY","Cannot unload an empty name");if(!t.default.unloadAsync)throw new o.UnavailabilityError('expo-font','unloadAsync');await t.default.unloadAsync(e,n)}}