/**
 * Module ID: 216
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 216);
const m = module;
const _e = exports;
const d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";function e(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(_e,'__esModule',{value:!0}),Object.defineProperty(_e,"MainNavigator",{enumerable:!0,get:function(){return k}});var t=require("./module_37"),n=e(t),o=e(require("./default_144")),s=e(require("./default_217")),c=e(require("./default_45"));require("./module_98");var l=e(require("./default_218")),u=require("./createBottomTabNavigator_225"),b=require("./module_233"),h=require("./module_420"),p=require("./JP_useScoreStore_174"),S=require("./IS_WEB_199"),f=require("./module_592"),x=require("./JP_RecordScreen_593"),y=require("./JP_HistoryScreen_692"),F=require("./JP_AnalysisScreen_1000"),j=require("./JP_MemberScreen_1022"),AttendanceScreen=require("./AttendanceScreen").AttendanceScreen,v=require("./JP_SettingsScreen_1023"),B=require("./JP_AIChatBot_1034"),T=require("./module_427");const A={prefixes:['http://localhost:8081','https://archery-record-app.web.app','https://kyudoscoremanager.web.app'],config:{screens:{'\u8a18\u9332':'record','\u5c65\u6b74':'history','\u5206\u6790':'analysis','\u30e1\u30f3\u30d0\u30fc':'members',
'\u51fa\u6b20':'attendance',
'\u8a2d\u5b9a':'settings'}}},C=(0,u.createBottomTabNavigator)(),w=Object.assign({},b.DefaultTheme,{colors:Object.assign({},b.DefaultTheme.colors,{background:'#FFFFFF',card:'#FFFFFF'})});const D=c.default.create({tabBarWrapper:Object.assign({position:'absolute',top:0,left:0,right:0,zIndex:1e3},S.IS_WEB?{backdropFilter:'blur(10px)',WebkitBackdropFilter:'blur(10px)'}:{}),tabBarContainer:{flexDirection:'row',alignItems:'center',justifyContent:'center',paddingHorizontal:8,height:54},leftActions:{display:'none'},tabItems:{flexDirection:'row',backgroundColor:'#E5E5EA',borderRadius:24,padding:3},tabButton:{paddingHorizontal:12,paddingVertical:6,borderRadius:20,minWidth:45,alignItems:'center'},tabButtonActive:Object.assign({backgroundColor:'#FFFFFF'},(0,f.getShadowStyle)({shadowOffset:{width:0,height:1},shadowOpacity:.1,shadowRadius:1,elevation:2})),tabText:{fontSize:13,color:'#3A3A3C',fontWeight:'500'},tabTextActive:{fontWeight:'bold',color:'#000'},tabButtonHover:{backgroundColor:'rgba(255, 255, 255, 0.5)'},tabTextHoverable:{},rightActions:{display:'none'},pagination:{flexDirection:'row',gap:20,marginRight:4},pageBtn:{padding:4},adminActions:{flexDirection:'row',alignItems:'center',gap:16},editBtn:{paddingVertical:4},editText:{color:'#5856D6',fontSize:17,fontWeight:'400'},trashBtn:{padding:4},badgeDot:{width:6,height:6,borderRadius:3,backgroundColor:'#007AFF',marginLeft:2,marginTop:-8}});

const I=n.default.memo(({state:e,descriptors:t,navigation:n})=>{(0,h.useSafeAreaInsets)();const c=(0,p.useScoreStore)(e=>e.historySelectedTags||[]),u=(0,p.useScoreStore)(e=>e.analysisSelectedTags||[]),b=(0,p.useScoreStore)(e=>e.currentSessionTags||[]),f=((0,p.useScoreStore)(e=>e.toggleHistoryTag),(0,p.useScoreStore)(e=>e.toggleAnalysisTag),(0,p.useScoreStore)(e=>e.toggleCurrentSessionTag),(0,p.useScoreStore)(e=>e.setHistorySelectedTags),(0,p.useScoreStore)(e=>e.setAnalysisSelectedTags),(0,p.useScoreStore)(e=>e.setCurrentSessionTags),e.routes[e.index].name),x=S.IS_WEB?o.default:h.SafeAreaView;return console.log('[CustomTabBar] Active Route:',f,'Tags:',{current:b.length,history:c.length,analysis:u.length}),(0,T.jsx)(x,{style:[D.tabBarWrapper,S.IS_WEB&&{paddingTop:0}],edges:['top','left','right'],children:(0,T.jsxs)(o.default,{style:[D.tabBarContainer,{backgroundColor:'#FFFFFF',height:60}],children:[(0,T.jsx)(o.default,{style:D.leftActions}),(0,T.jsx)(o.default,{style:D.tabItems,children:e.routes.map((h,p)=>{const{options:S}=t[h.key],f=void 0!==S.tabBarLabel?S.tabBarLabel:void 0!==S.title?S.title:h.name,x=e.index===p;let y=!1;'\u8a18\u9332'===h.name&&b.length>0&&(y=!0),'\u5c65\u6b74'===h.name&&c.length>0&&(y=!0),'\u5206\u6790'===h.name&&u.length>0&&(y=!0);return(0,T.jsx)(l.default,{onPress:()=>{const e=n.emit({type:'tabPress',target:h.key,canPreventDefault:!0});x||e.defaultPrevented||n.navigate(h.name)},style:({pressed:e,hovered:t})=>[D.tabButton,x&&D.tabButtonActive,!x&&t&&D.tabButtonHover,e&&{opacity:.7}],children:(0,T.jsxs)(o.default,{style:{flexDirection:'row',alignItems:'center'},children:[(0,T.jsx)(s.default,{style:[D.tabText,x&&D.tabTextActive,!x&&D.tabTextHoverable],children:f}),y&&(0,T.jsx)(o.default,{style:D.badgeDot})]})},p)})}),(0,T.jsx)(o.default,{style:D.rightActions})]})})});

const Record = x.RecordScreen;
const History = y.HistoryScreen;
const Analysis = F.AnalysisScreen;
const Members = j.MemberScreen;
const Attendance = AttendanceScreen;
const Settings = v.SettingsScreen;

const k=()=>{const e=(0,h.useSafeAreaInsets)(),n=(0,p.useScoreStore)(e=>e.activeRole),o=(0,p.useScoreStore)(e=>e.setCurrentRouteName),s=(S.IS_WEB?S.WEB_TOP_PADDING:Math.max(e.top,20),(0,t.useCallback)(e=>(0,T.jsx)(I,Object.assign({},e)),[])),c=(0,t.useMemo)(()=>A,[]),l=(0,b.useNavigationContainerRef)();return(0,T.jsxs)(b.NavigationContainer,{ref:l,theme:w,linking:c,onStateChange:()=>{const e=l.getCurrentRoute();e&&o(e.name)},onReady:()=>{const e=l.getCurrentRoute();e&&o(e.name)},children:[(0,T.jsxs)(C.Navigator,{tabBar:s,screenOptions:{headerShown:!1},children:[(0,T.jsx)(C.Screen,{name:"\u8a18\u9332",component:Record}),(0,T.jsx)(C.Screen,{name:"\u5c65\u6b74",component:History}),(0,T.jsx)(C.Screen,{name:"\u5206\u6790",component:Analysis}),'group'===n&&(0,T.jsx)(C.Screen,{name:"\u30e1\u30f3\u30d0\u30fc",component:Members}),
'group'===n&&(0,T.jsx)(C.Screen,{name:"\u51fa\u6b20",component:Attendance}),
(0,T.jsx)(C.Screen,{name:"\u8a2d\u5b9a",component:Settings})]}),(0,T.jsx)(B.AIChatBot,{})]})};