/**
 * Module ID: 539
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 539);
const m = module;
const _e = exports;
const _d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";function e(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(_e,'__esModule',{value:!0}),_e.HeaderBackButton=function({disabled:e,allowFontScaling:o,backImage:h,label:p,labelStyle:x,displayMode:L="minimal",onLabelLayout:j,onPress:O,pressColor:k,pressOpacity:w,screenLayout:C,tintColor:_,titleLayout:v,truncatedLabel:I="Back",accessibilityLabel:M=(p&&'Back'!==p?`${p}, back`:'Go back'),testID:S,style:W,href:B}){const{colors:D,fonts:E}=(0,t.useTheme)(),{direction:F}=(0,t.useLocale)(),[H,P]=n.useState(null),[N,T]=n.useState(null);return(0,f.jsx)(u.HeaderButton,{disabled:e,href:B,accessibilityLabel:M,testID:S,onPress:()=>{O&&requestAnimationFrame(()=>O())},pressColor:k,pressOpacity:w,style:[y.container,W],children:(0,f.jsxs)(n.Fragment,{children:[h?h({tintColor:_??D.text}):(0,f.jsx)(d.HeaderIcon,{source:c.default,tintColor:_,style:[y.icon,'minimal'!==L&&y.iconWithLabel]}),(()=>{if('minimal'===L)return null;const e=v&&C?(C.width-v.width)/2-(b+d.ICON_MARGIN):null,t='default'===L?p:I,n=e&&H&&N?e>H?t:e>N?I:null:t,c=[E.regular,y.label,x],u=[c,{position:'absolute',top:0,left:0,opacity:0}];return(0,f.jsxs)(s.default,{style:y.labelWrapper,children:[p&&'default'===L?(0,f.jsx)(l.default.Text,{style:u,numberOfLines:1,onLayout:e=>P(e.nativeEvent.layout.width),children:p}):null,I?(0,f.jsx)(l.default.Text,{style:u,numberOfLines:1,onLayout:e=>T(e.nativeEvent.layout.width),children:I}):null,n?(0,f.jsx)(l.default.Text,{accessible:!1,onLayout:j,style:[_?{color:_}:null,c],numberOfLines:1,allowFontScaling:!!o,children:n}):null]})})()]})})};var t=require("./module_233"),n=(function(e){if(e&&e.__esModule)return e;var t={};return e&&Object.keys(e).forEach(function(n){var l=Object.getOwnPropertyDescriptor(e,n);Object.defineProperty(t,n,l.get?l:{enumerable:!0,get:function(){return e[n]}})}),t.default=e,t})(require("./module_37")),l=e(require("./default_286"));e(require("./default_339"));require("./module_98");var o=e(require("./default_45")),s=e(require("./default_144")),c=e(require("./module_516")),u=(e(require("./module_517")),require("./module_540"),require("./HeaderButton_541")),d=require("./ICON_SIZE_542"),f=require("./module_254");const b=24,y=o.default.create({container:Object.assign({paddingHorizontal:0,minWidth:o.default.hairlineWidth},{marginVertical:3,marginHorizontal:11}),label:{fontSize:17,letterSpacing:.35},labelWrapper:{flexDirection:'row',alignItems:'flex-start',marginEnd:d.ICON_MARGIN},icon:{width:b,marginEnd:3},iconWithLabel:{},iconMaskContainer:{flex:1,flexDirection:'row',justifyContent:'center'},iconMaskFillerRect:{flex:1,backgroundColor:'#000'},iconMask:{height:21,width:13,marginStart:-14.5,marginVertical:12,alignSelf:'center'},flip:{transform:'scaleX(-1)'}})