/**
 * Module ID: 857
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const _a = (typeof id !== 'undefined' ? id : 857);
const m = module;
const e = exports;
const d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";Object.defineProperty(e,'__esModule',{value:!0}),Object.defineProperty(e,"default",{enumerable:!0,get:function(){return T}}),Object.defineProperty(e,"longFormatters",{enumerable:!0,get:function(){return n.longFormatters}}),Object.defineProperty(e,"parsers",{enumerable:!0,get:function(){return f.parsers}}),e.parse=y;var t=require("./module_788"),n=require("./module_807"),o=require("./module_808"),a=require("./module_699"),s=require("./module_827"),c=require("./module_701"),l=require("./u_858"),f=require("./module_860");const u=/[yYQqMLwIdDecihHKkms]o|(\w)\1*|''|'(''|[^'])+('|$)|./g,p=/P+p+|P+|p+|''|'(''|[^'])+('|$)|./g,k=/^'([^]*?)'?$/,h=/''/g,w=/\S/,O=/[a-zA-Z]/;function y(k,h,y,T){const D=()=>(0,a.constructFrom)(T?.in||y,NaN),P=(0,s.getDefaultOptions)(),A=T?.locale??P.locale??t.defaultLocale,S=T?.firstWeekContainsDate??T?.locale?.options?.firstWeekContainsDate??P.firstWeekContainsDate??P.locale?.options?.firstWeekContainsDate??1,W=T?.weekStartsOn??T?.locale?.options?.weekStartsOn??P.weekStartsOn??P.locale?.options?.weekStartsOn??0;if(!h)return k?D():(0,c.toDate)(y,T?.in);const j={firstWeekContainsDate:S,weekStartsOn:W,locale:A},F=[new l.DateTimezoneSetter(T?.in,y)],$=h.match(p).map(t=>{const o=t[0];if(o in n.longFormatters){return(0,n.longFormatters[o])(t,A.formatLong)}return t}).join("").match(u),C=[];for(let t of $){!T?.useAdditionalWeekYearTokens&&(0,o.isProtectedWeekYearToken)(t)&&(0,o.warnOrThrowProtectedError)(t,h,k),!T?.useAdditionalDayOfYearTokens&&(0,o.isProtectedDayOfYearToken)(t)&&(0,o.warnOrThrowProtectedError)(t,h,k);const n=t[0],a=f.parsers[n];if(a){const{incompatibleTokens:o}=a;if(Array.isArray(o)){const a=C.find(t=>o.includes(t.token)||t.token===n);if(a)throw new RangeError(`The format string mustn't contain \`${a.fullToken}\` and \`${t}\` at the same time`)}else if("*"===a.incompatibleTokens&&C.length>0)throw new RangeError(`The format string mustn't contain \`${t}\` and any other token at the same time`);C.push({token:n,fullToken:t});const s=a.run(k,t,A.match,j);if(!s)return D();F.push(s.setter),k=s.rest}else{if(n.match(O))throw new RangeError("Format string contains an unescaped latin alphabet character `"+n+"`");if("''"===t?t="'":"'"===n&&(t=b(t)),0!==k.indexOf(t))return D();k=k.slice(t.length)}}if(k.length>0&&w.test(k))return D();const E=F.map(t=>t.priority).sort((t,n)=>n-t).filter((t,n,o)=>o.indexOf(t)===n).map(t=>F.filter(n=>n.priority===t).sort((t,n)=>n.subPriority-t.subPriority)).map(t=>t[0]);let Y=(0,c.toDate)(y,T?.in);if(isNaN(+Y))return D();const v={};for(const t of E){if(!t.validate(Y,j))return D();const n=t.set(Y,v,j);Array.isArray(n)?(Y=n[0],Object.assign(v,n[1])):Y=n}return Y}function b(t){return t.match(k)[1].replace(h,"'")}var T=y