/**
 * Module ID: 953
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 953);
const m = module;
const e = exports;
const d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";Object.defineProperty(e,'__esModule',{value:!0}),Object.defineProperty(e,"default",{enumerable:!0,get:function(){return $}}),e.parseISO=o;var t=require("./module_700"),n=require("./module_699"),u=require("./module_701");function o(t,o){const s=()=>(0,n.constructFrom)(o?.in,NaN),c=o?.additionalDigits??2,l=N(t);let f;if(l.date){const t=D(l.date,c);f=T(t.restDateString,t.year)}if(!f||isNaN(+f))return s();const p=+f;let U,I=0;if(l.time&&(I=C(l.time),isNaN(I)))return s();if(!l.timezone){const t=new Date(p+I),n=(0,u.toDate)(0,o?.in);return n.setFullYear(t.getUTCFullYear(),t.getUTCMonth(),t.getUTCDate()),n.setHours(t.getUTCHours(),t.getUTCMinutes(),t.getUTCSeconds(),t.getUTCMilliseconds()),n}return U=h(l.timezone),isNaN(U)?s():(0,u.toDate)(p+I+U,o?.in)}const s={dateTimeDelimiter:/[T ]/,timeZoneDelimiter:/[Z ]/i,timezone:/([Z+-].*)$/},c=/^-?(?:(\d{3})|(\d{2})(?:-?(\d{2}))?|W(\d{2})(?:-?(\d{1}))?|)$/,l=/^(\d{2}(?:[.,]\d*)?)(?::?(\d{2}(?:[.,]\d*)?))?(?::?(\d{2}(?:[.,]\d*)?))?$/,f=/^([+-])(\d{2})(?::?(\d{2}))?$/;function N(t){const n={},u=t.split(s.dateTimeDelimiter);let o;if(u.length>2)return n;if(/:/.test(u[0])?o=u[0]:(n.date=u[0],o=u[1],s.timeZoneDelimiter.test(n.date)&&(n.date=t.split(s.timeZoneDelimiter)[0],o=t.substr(n.date.length,t.length))),o){const t=s.timezone.exec(o);t?(n.time=o.replace(t[1],""),n.timezone=t[1]):n.time=o}return n}function D(t,n){const u=new RegExp("^(?:(\\d{4}|[+-]\\d{"+(4+n)+"})|(\\d{2}|[+-]\\d{"+(2+n)+"})$)"),o=t.match(u);if(!o)return{year:NaN,restDateString:""};const s=o[1]?parseInt(o[1]):null,c=o[2]?parseInt(o[2]):null;return{year:null===c?s:100*c,restDateString:t.slice((o[1]||o[2]).length)}}function T(t,n){if(null===n)return new Date(NaN);const u=t.match(c);if(!u)return new Date(NaN);const o=!!u[4],s=p(u[1]),l=p(u[2])-1,f=p(u[3]),N=p(u[4]),D=p(u[5])-1;if(o)return Z(n,N,D)?I(n,N,D):new Date(NaN);{const t=new Date(0);return y(n,l,f)&&F(n,s)?(t.setUTCFullYear(n,l,Math.max(s,f)),t):new Date(NaN)}}function p(t){return t?parseInt(t):1}function C(n){const u=n.match(l);if(!u)return NaN;const o=U(u[1]),s=U(u[2]),c=U(u[3]);return z(o,s,c)?o*t.millisecondsInHour+s*t.millisecondsInMinute+1e3*c:NaN}function U(t){return t&&parseFloat(t.replace(",","."))||0}function h(n){if("Z"===n)return 0;const u=n.match(f);if(!u)return 0;const o="+"===u[1]?-1:1,s=parseInt(u[2]),c=u[3]&&parseInt(u[3])||0;return S(s,c)?o*(s*t.millisecondsInHour+c*t.millisecondsInMinute):NaN}function I(t,n,u){const o=new Date(0);o.setUTCFullYear(t,0,4);const s=7*(n-1)+u+1-(o.getUTCDay()||7);return o.setUTCDate(o.getUTCDate()+s),o}const w=[31,null,31,30,31,30,31,31,30,31,30,31];function M(t){return t%400==0||t%4==0&&t%100!=0}function y(t,n,u){return n>=0&&n<=11&&u>=1&&u<=(w[n]||(M(t)?29:28))}function F(t,n){return n>=1&&n<=(M(t)?366:365)}function Z(t,n,u){return n>=1&&n<=53&&u>=0&&u<=6}function z(t,n,u){return 24===t?0===n&&0===u:u>=0&&u<60&&n>=0&&n<60&&t>=0&&t<25}function S(t,n){return n>=0&&n<=59}var $=o