/**
 * Module ID: 470
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const _r = require;
const _i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 470);
const m = module;
const _e = exports;
const _d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";Object.defineProperty(_e,'__esModule',{value:!0}),_e.useDescriptors=function({state:e,screens:t,navigation:f,screenOptions:v,screenLayout:y,onAction:h,getState:b,setState:k,addListener:O,addKeyedListener:j,onRouteFocus:C,router:S,emitter:x}){const _=o.useContext(u.ThemeContext),[w,P]=o.useState({}),{onDispatchAction:L,onOptionsChange:N,scheduleUpdate:R,flushUpdates:A,stackRef:D}=o.useContext(r.NavigationBuilderContext),M=o.useMemo(()=>({navigation:f,onAction:h,addListener:O,addKeyedListener:j,onRouteFocus:C,onDispatchAction:L,onOptionsChange:N,scheduleUpdate:R,flushUpdates:A,stackRef:D}),[f,h,O,j,C,L,N,R,A,D]),{base:U,navigations:B}=(0,c.useNavigationCache)({state:e,getState:b,navigation:f,setOptions:P,router:S,emitter:x}),E=(0,d.useRouteCache)(e.routes),F=(e,n,o)=>{const r=t[e.name],i=r.props;return[v,...r.options?r.options.filter(Boolean):[],i.options,o].reduce((t,o)=>Object.assign(t,'function'!=typeof o?o:o({route:e,navigation:n,theme:_})),{})},K=(e,o,u,c)=>{const d=t[e.name],f=d.props,v=f.layout??d.layout??y;let h=(0,p.jsx)(s.SceneView,{navigation:o,route:e,screen:f,routeState:c,getState:b,setState:k,options:u,clearOptions:()=>P(t=>{if(e.key in t){var o;return(0,n.default)(t,[o].map(l))}return t})});return null!=v&&(h=v({route:e,navigation:o,options:u,theme:_,children:h})),(0,p.jsx)(r.NavigationBuilderContext.Provider,{value:M,children:(0,p.jsx)(i.NavigationProvider,{route:e,navigation:o,children:h})},e.key)},T=E.reduce((t,n,o)=>{const r=B[n.key],i=F(n,r,w[n.key]),s=K(n,r,i,e.routes[o].state);return t[n.key]={route:n,navigation:r,render:()=>s,options:i},t},{});return{describe:(e,t)=>{if(!t){if(!(e.key in T))throw new Error(`Couldn't find a route with the key ${e.key}.`);return T[e.key]}const n=U,o=F(e,n,{}),r=K(e,n,o,void 0);return{route:e,navigation:n,render:()=>r,options:o}},descriptors:T}};var e,t=require("./module_130"),n=(e=t)&&e.__esModule?e:{default:e},o=(function(e){if(e&&e.__esModule)return e;var t={};return e&&Object.keys(e).forEach(function(n){var o=Object.getOwnPropertyDescriptor(e,n);Object.defineProperty(t,n,o.get?o:{enumerable:!0,get:function(){return e[n]}})}),t.default=e,t})(require("./module_37")),r=require("./NavigationBuilderContext_257"),i=require("./NavigationRouteContext_435"),s=require("./module_471"),u=require("./ThemeContext_262"),c=require("./module_474"),d=require("./CHILD_STATE_442"),p=require("./module_254");function l(e){var t=f(e,"string");return"symbol"==typeof t?t:t+""}function f(e,t){if("object"!=typeof e||!e)return e;var n=e[Symbol.toPrimitive];if(void 0!==n){var o=n.call(e,t||"default");if("object"!=typeof o)return o;throw new TypeError("@@toPrimitive must return a primitive value.")}return("string"===t?String:Number)(e)}