/**
 * Module ID: 444
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 444);
const m = module;
const _e = exports;
const _d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";Object.defineProperty(_e,'__esModule',{value:!0}),_e.getPathFromState=function(t,o){if(null==t)throw Error(`Got '${String(t)}' for the navigation state. You must pass a valid state object.`);o&&(0,n.validatePathConfig)(o);const f=c(o);let p='/',u=t;const d={};for(;u;){let n,o,c='number'==typeof u.index?u.index:0,l=u.routes[c],h=f;const b=s(t),y=[];let j=!0;for(;l.name in h&&j;){if(n=h[l.name].parts,y.push(l.name),l.params){const e=h[l.name],t=Object.fromEntries(Object.entries(l.params).map(([t,n])=>{if(void 0===n){if(!e)return null;{const n=e.parts?.find(e=>e.param===t)?.optional;if(n)return null}}return[t,(e?.stringify?.[t]??String)(n)]}).filter(e=>null!=e));n?.length&&Object.assign(d,t),b===l&&(o=Object.assign({},t),n?.forEach(({param:e})=>{e&&o&&delete o[e]}))}if(h[l.name].screens&&void 0!==l.state){c='number'==typeof l.state.index?l.state.index:l.state.routes.length-1;const e=l.state.routes[c],t=h[l.name].screens;t&&e.name in t?(l=e,h=t):j=!1}else j=!1}if(void 0!==h[l.name]?p+=n?.map(({segment:e,param:t,optional:n})=>{if('*'===e)return l.name;if(t){const e=d[t];return void 0===e&&n?'':Array.from(String(e)).map(e=>/[^A-Za-z0-9\-._~!$&'()*+,;=:@]/g.test(e)?encodeURIComponent(e):e).join('')}return encodeURIComponent(e)}).join('/'):p+=encodeURIComponent(l.name),!o&&b.params&&(o=Object.fromEntries(Object.entries(b.params).map(([e,t])=>[e,String(t)]))),l.state)p+='/';else if(o){for(const e in o)'undefined'===o[e]&&delete o[e];const t=e.stringify(o,{sort:!1});t&&(p+=`?${t}`)}u=l.state}o?.path&&(p=`${o.path}/${p}`);p=p.replace(/\/+/g,'/'),p=p.length>1?p.replace(/\/$/,''):p,p.startsWith('/')||(p=`/${p}`);return p};var e=(function(e){if(e&&e.__esModule)return e;var t={};return e&&Object.keys(e).forEach(function(n){var s=Object.getOwnPropertyDescriptor(e,n);Object.defineProperty(t,n,s.get?s:{enumerable:!0,get:function(){return e[n]}})}),t.default=e,t})(require("./module_445")),t=require("./module_450"),n=require("./module_451");const s=e=>{const t='number'==typeof e.index?e.routes[e.index]:e.routes[e.routes.length-1];return t.state?s(t.state):t},o=new WeakMap,c=e=>{if(!e?.screens)return{};const t=o.get(e?.screens);if(t)return t;const n=p(e.screens);return o.set(e.screens,n),n};const f=(e,n)=>{if('string'==typeof e){const s=(0,t.getPatternParts)(e);return n?{parts:[...n,...s]}:{parts:s}}if(e.exact&&void 0===e.path)throw new Error("A 'path' needs to be specified when specifying 'exact: true'. If you don't want this screen in the URL, specify it as empty string, e.g. `path: ''`.");const s=!0!==e.exact?[...n||[],...e.path?(0,t.getPatternParts)(e.path):[]]:e.path?(0,t.getPatternParts)(e.path):void 0,o=e.screens?p(e.screens,s):void 0;return{parts:s,stringify:e.stringify,screens:o}},p=(e,t)=>Object.fromEntries(Object.entries(e).map(([e,n])=>[e,f(n,t)]))