/**
 * Module ID: 211
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 211);
const m = module;
const e = exports;
const d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";Object.defineProperty(e,'__esModule',{value:!0}),Object.defineProperty(e,"default",{enumerable:!0,get:function(){return y}});var n=require("./module_212"),t=require("./module_213");const o='undefined'!=typeof window,s=!o||window.hasOwnProperty('tizen')||window.hasOwnProperty('webOS')?void 0:window.navigator.connection||window.navigator.mozConnection||window.navigator.webkitConnection,l={bluetooth:t.NetInfoStateType.bluetooth,cellular:t.NetInfoStateType.cellular,ethernet:t.NetInfoStateType.ethernet,none:t.NetInfoStateType.none,other:t.NetInfoStateType.other,unknown:t.NetInfoStateType.unknown,wifi:t.NetInfoStateType.wifi,wimax:t.NetInfoStateType.wimax,mixed:t.NetInfoStateType.other},c={'2g':t.NetInfoCellularGeneration['2g'],'3g':t.NetInfoCellularGeneration['3g'],'4g':t.NetInfoCellularGeneration['4g'],'slow-2g':t.NetInfoCellularGeneration['2g']},u=n=>{const u=!!o&&navigator.onLine,p={isInternetReachable:null};if(!s){if(u){return Object.assign({},p,{isConnected:!0,type:t.NetInfoStateType.other,details:{isConnectionExpensive:!1}})}return Object.assign({},p,{isConnected:!1,isInternetReachable:!1,type:t.NetInfoStateType.none,details:null})}const f=s.saveData,y=s.type?l[s.type]:u?t.NetInfoStateType.other:t.NetInfoStateType.unknown;if(y===t.NetInfoStateType.bluetooth){return Object.assign({},p,{isConnected:!0,type:y,details:{isConnectionExpensive:f}})}if(y===t.NetInfoStateType.cellular){return Object.assign({},p,{isConnected:!0,type:y,details:{isConnectionExpensive:f,cellularGeneration:c[s.effectiveType]||null,carrier:null}})}if(y===t.NetInfoStateType.ethernet){return Object.assign({},p,{isConnected:!0,type:y,details:{isConnectionExpensive:f,ipAddress:null,subnet:null}})}if(y===t.NetInfoStateType.wifi){return Object.assign({},p,{isConnected:!0,type:y,details:{isConnectionExpensive:f,ssid:null,bssid:null,strength:null,ipAddress:null,subnet:null,frequency:null,linkSpeed:null,rxLinkSpeed:null,txLinkSpeed:null}})}if(y===t.NetInfoStateType.wimax){return Object.assign({},p,{isConnected:!0,type:y,details:{isConnectionExpensive:f}})}if(y===t.NetInfoStateType.none){return Object.assign({},p,{isConnected:!1,isInternetReachable:!1,type:y,details:null})}if(y===t.NetInfoStateType.unknown){return Object.assign({},p,{isConnected:u,isInternetReachable:null,type:y,details:null})}return Object.assign({},p,{isConnected:!0,type:t.NetInfoStateType.other,details:{isConnectionExpensive:f}})},p=[],f=[];var y={addListener(t,l){switch(t){case n.DEVICE_CONNECTIVITY_EVENT:{const n=()=>{l(u())};s?s.addEventListener('change',n):o&&(window.addEventListener('online',n,!1),window.addEventListener('offline',n,!1)),p.push(l),f.push(n);break}}},removeListeners(t,l){switch(t){case n.DEVICE_CONNECTIVITY_EVENT:{const n=p.indexOf(l),t=f[n];s?s.removeEventListener('change',t):o&&(window.removeEventListener('online',t),window.removeEventListener('offline',t)),p.splice(n,1),f.splice(n,1);break}}},getCurrentState:async n=>u(),configure(){}}