/**
 * Module ID: 277
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 277);
const m = module;
const e = exports;
const d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.transformKeys=e.inlineSpecificity=e.SpecificityIndex=e.STYLE_SCOPES=e.DEFAULT_CONTAINER_NAME=e.PLACEHOLDER_SYMBOL=e.StyleRuleSymbol=e.StyleRuleSetSymbol=e.INTERNAL_FLAGS=e.INTERNAL_SET=e.INTERNAL_RESET=void 0,e.isDescriptorFunction=function(t){return Array.isArray(t)&&"object"==typeof t[0]&&!Array.isArray(t[0])},e.isDescriptorArray=function(t){if(Array.isArray(t))return"object"!=typeof t[0]||Array.isArray(t[0]);return!1},e.isRuntimeDescriptor=function(t){return!("object"!=typeof t||!Array.isArray(t))||"object"!=typeof t},e.assignToTarget=function s(n,o,y,l={}){if("object"==typeof o&&t.ShorthandSymbol in o)return o.map(t=>{let o=Array.from(Array.isArray(y)?y:y.target);const f=t[0];"string"==typeof f?o.splice(-1,1,f):o.splice(-1,1,...f),s(n,t[1],o,l)});const{arrayMergeStyle:f="push",objectMergeStyle:c="assign",allowTransformMerging:A=!1,reverseTransformPush:S=!1}=l;let u,b=Array.isArray(y)?y:y.target;if(0===b.length)return void Object.assign(n,o);for(let t=0;t<b.length-1;t++)u=b[t],Array.isArray(n)&&isFinite(Number(u))&&(u=Number(u)),"object"!=typeof n[u]?n[u]={}:Object.isFrozen(n[u])&&(n[u]=Object.assign({},n[u])),n=n[u];if(u=b[b.length-1],A&&e.transformKeys.has(u)){let t;Array.isArray(n.transform)?t=n.transform.find(t=>u in t):n.transform=[],t?t[u]=o:S?n.transform.shift({[u]:o}):n.transform.push({[u]:o})}else{const t=n[u];if(Array.isArray(t)){if("push"===f)t.push(o)}else if("object"==typeof t&&t&&!(e.PLACEHOLDER_SYMBOL in t))switch(c){case"assign":n[u]="object"==typeof o?Object.assign({},n[u],o):o;break;case"toArray":n[u]=[t,o]}else!o||"object"!=typeof o||"_isReanimatedSharedValue"in o||e.PLACEHOLDER_SYMBOL in o||Array.isArray(o)?n[u]=o:n[u]=Object.assign({},o)}},e.getTargetValue=function(t,s){let n;s="string"==typeof s?[s]:s;for(let o=0;o<s.length-1;o++)n=s[o],Array.isArray(t)&&isFinite(Number(n))&&(n=Number(n)),"object"!=typeof t[n]&&(t[n]={}),t=t[n];if(n=s[s.length-1],e.transformKeys.has(n)){let s;return Array.isArray(t.transform)?s=t.transform.find(t=>n in t):t.transform=[],s?.[n]}return t[n]};const t=require("./module_278");e.INTERNAL_RESET=Symbol(),e.INTERNAL_SET=Symbol(),e.INTERNAL_FLAGS=Symbol(),e.StyleRuleSetSymbol=Symbol(),e.StyleRuleSymbol=Symbol(),e.PLACEHOLDER_SYMBOL=Symbol(),e.DEFAULT_CONTAINER_NAME="@__",e.STYLE_SCOPES={GLOBAL:0,CONTEXT:1,SELF:2},e.SpecificityIndex={Order:0,ClassName:1,Important:2,Inline:3,PseudoElements:4},e.inlineSpecificity=[],e.inlineSpecificity[e.SpecificityIndex.Inline]=1,e.transformKeys=new Set(["translateX","translateY","scale","scaleX","scaleY","rotate","rotateX","rotateY","rotateZ","skewX","skewY","perspective","matrix","transformOrigin"])