/**
 * Module ID: 492
 */
"use strict";

const g = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this);
const r = require;
const i = (typeof metroImport !== 'undefined' ? metroImport : undefined);
const a = (typeof id !== 'undefined' ? id : 492);
const m = module;
const _e = exports;
const _d = (typeof dependencyMap !== 'undefined' ? dependencyMap : []);

"use strict";const e=["direction","theme","linking","fallback","documentTitle","onReady","onStateChange"];function t(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(_e,'__esModule',{value:!0}),Object.defineProperty(_e,"NavigationContainer",{enumerable:!0,get:function(){return j}});var n=t(require("./module_130")),o=require("./module_235"),l=(function(e){if(e&&e.__esModule)return e;var t={};return e&&Object.keys(e).forEach(function(n){var o=Object.getOwnPropertyDescriptor(e,n);Object.defineProperty(t,n,o.get?o:{enumerable:!0,get:function(){return e[n]}})}),t.default=e,t})(require("./module_37")),u=t(require("./module_370")),c=t(require("./default_247")),s=require("./LinkingContext_493"),d=require("./LocaleDirContext_494"),f=require("./module_495"),h=require("./UnhandledLinkingContext_497"),S=require("./module_498"),v=require("./module_499"),b=require("./series_500"),P=require("./module_503"),C=require("./module_254");function O(t,O){let{direction:j=(u.default.getConstants().isRTL?'rtl':'ltr'),theme:T=f.DefaultTheme,linking:k,fallback:p=null,documentTitle:x,onReady:_,onStateChange:L}=t,R=(0,n.default)(t,e);const A=!!k&&!1!==k.enabled;k?.config&&(0,o.validatePathConfig)(k.config);const F=l.useRef(null);(0,S.useBackButton)(F),(0,v.useDocumentTitle)(F,x);const[y,D]=l.useState(),{getInitialState:E}=(0,b.useLinking)(F,Object.assign({enabled:A,prefixes:[]},k),D),I=l.useMemo(()=>({options:k}),[k]),M=l.useMemo(()=>({lastUnhandledLink:y,setLastUnhandledLink:D}),[y,D]),N=(0,c.default)(()=>{const e=F.current?.getCurrentRoute()?.path;D(t=>{if(t!==e)return t}),_?.()}),V=(0,c.default)(e=>{const t=F.current?.getCurrentRoute()?.path;D(e=>{if(e!==t)return e}),L?.(e)});l.useEffect(()=>{F.current&&REACT_NAVIGATION_DEVTOOLS.set(F.current,{get linking(){return Object.assign({},k,{enabled:A,prefixes:k?.prefixes??[],getStateFromPath:k?.getStateFromPath??o.getStateFromPath,getPathFromState:k?.getPathFromState??o.getPathFromState,getActionFromState:k?.getActionFromState??o.getActionFromState})}})});const[w,B]=(0,P.useThenable)(E);l.useImperativeHandle(O,()=>F.current);return null!=R.initialState||!A||w?(0,C.jsx)(d.LocaleDirContext.Provider,{value:j,children:(0,C.jsx)(h.UnhandledLinkingContext.Provider,{value:M,children:(0,C.jsx)(s.LinkingContext.Provider,{value:I,children:(0,C.jsx)(o.BaseNavigationContainer,Object.assign({},R,{theme:T,onReady:N,onStateChange:V,initialState:null==R.initialState?B:R.initialState,ref:F}))})})}):(0,C.jsx)(d.LocaleDirContext.Provider,{value:j,children:(0,C.jsx)(o.ThemeProvider,{value:T,children:p})})}globalThis.REACT_NAVIGATION_DEVTOOLS=new WeakMap;const j=l.forwardRef(O)