'use strict';

/**
 * 写真から記録を読み取る窓の見た目の決まり（2026-10-05 に OCRRecordModal.js から移した）。
 */
const { StyleSheet } = require('./rn');

const styles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  container: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '88%',
    minHeight: '50%',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#EEE',
  },
  headerTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  headerTitle: { fontSize: 16, fontWeight: 'bold', color: '#1C1C1E' },
  closeBtn: { padding: 4 },
  body: { flexGrow: 0 },
  hint: { fontSize: 13, color: '#666', marginBottom: 12, lineHeight: 18 },
  settingLabel: { fontSize: 13, fontWeight: '600', color: '#000', marginBottom: 6 },
  settingNote: { fontSize: 12, color: '#8E8E93', marginBottom: 14, lineHeight: 17 },

  thumbRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 12 },
  thumbWrap: { alignItems: 'center' },
  thumb: { width: 80, height: 80, borderRadius: 8, backgroundColor: '#EEE' },
  thumbRemove: { position: 'absolute', top: -6, right: -6, backgroundColor: '#FFF', borderRadius: 10 },
  thumbLabel: { fontSize: 10, color: '#888', marginTop: 2 },
  pickBtnRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  pickBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#007AFF',
    borderStyle: 'dashed',
    borderRadius: 10,
    paddingVertical: 14,
  },
  pickBtnText: { color: '#007AFF', fontSize: 15, fontWeight: '600' },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFF0F0',
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
  },
  errorText: { color: '#FF3B30', fontSize: 13, flex: 1 },
  analyzeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#007AFF',
    borderRadius: 10,
    paddingVertical: 14,
  },
  analyzeBtnDisabled: { backgroundColor: '#C7C7CC' },
  analyzeBtnText: { color: '#FFF', fontSize: 15, fontWeight: 'bold' },

  centerBox: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 40 },
  centerText: { marginTop: 14, fontSize: 14, color: '#666' },
  legendRow: { flexDirection: 'row', gap: 16, marginBottom: 14 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  legendDot: { width: 12, height: 12, borderRadius: 3 },
  legendText: { fontSize: 11, color: '#666' },
  tachiBlock: { marginBottom: 16 },
  tachiLabel: { fontSize: 13, fontWeight: 'bold', color: '#3C3C43', marginBottom: 6 },
  seatRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  seatChip: {
    minWidth: 64,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  seatChipText: { fontSize: 12, color: '#1C1C1E', textAlign: 'center' },

  // 読み取りモード切替（立ち順表 / 紙の記録）
  modeRow: {
    flexDirection: 'row',
    backgroundColor: '#F2F2F7',
    borderRadius: 10,
    padding: 3,
    marginBottom: 12,
  },
  modeBtn: { flex: 1, paddingVertical: 8, borderRadius: 8, alignItems: 'center' },
  modeBtnActive: { backgroundColor: '#FFFFFF' },
  modeBtnText: { fontSize: 14, color: '#8E8E93', fontWeight: '600' },
  modeBtnTextActive: { color: '#007AFF', fontWeight: 'bold' },

  // 紙の記録のプレビュー（1行＝1人）
  recordRow: { marginBottom: 14, padding: 10, backgroundColor: '#F9F9F9', borderRadius: 10 },
  recordRowHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 8 },
  recordNameChip: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    justifyContent: 'center',
  },
  recordNameText: { fontSize: 14, color: '#1C1C1E', fontWeight: '600' },
  recordScoreText: { fontSize: 13, color: '#8E8E93', fontWeight: 'bold', minWidth: 42, textAlign: 'right' },
  recordRemoveBtn: { padding: 4 },
  markRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  markCell: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E5EA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  markCellHit: { backgroundColor: '#E5F1FF', borderColor: '#007AFF' },
  markCellMiss: { backgroundColor: '#FFE5E5', borderColor: '#FF3B30' },
  // 端末の読み取りが迷ったマス。○×の文字色はそのまま、枠を太い黄色にして目に留める
  markCellMayoi: { borderWidth: 2, borderColor: '#FFB300', backgroundColor: '#FFF4CC' },
  legendDotMayoi: { backgroundColor: '#FFF4CC', borderWidth: 2, borderColor: '#FFB300' },
  markCellText: { fontSize: 16, color: '#C7C7CC', fontWeight: 'bold' },
  markCellTextHit: { color: '#007AFF' },
  markCellTextMiss: { color: '#FF3B30' },

  previewFooter: { flexDirection: 'row', gap: 10, padding: 16, borderTopWidth: 1, borderTopColor: '#EEE' },
  footerBtnSecondary: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: '#F2F2F7',
    alignItems: 'center',
  },
  footerBtnSecondaryText: { color: '#007AFF', fontSize: 15, fontWeight: '600' },
  footerBtnPrimary: {
    flex: 2,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: '#FF3B30',
    alignItems: 'center',
  },
  footerBtnPrimaryText: { color: '#FFF', fontSize: 15, fontWeight: 'bold' },
  pickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pickerBox: {
    width: '88%',
    maxWidth: 380,
    maxHeight: '70%',
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 16,
  },
  pickerTitle: { fontSize: 15, fontWeight: 'bold', marginBottom: 10, color: '#1C1C1E' },
  pickerSearchInput: {
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    marginBottom: 10,
  },
  pickerList: { maxHeight: 320 },
  pickerRow: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#F0F0F0' },
  pickerRowIndent: {
    paddingVertical: 12,
    paddingLeft: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  pickerRowText: { fontSize: 14, color: '#1C1C1E' },
  pickerRowTextMuted: { fontSize: 14, color: '#999' },
  pickerRowTextGuest: { fontSize: 14, color: '#FF9500', fontWeight: '600' },
  pickerCloseBtn: { marginTop: 10, paddingVertical: 10, alignItems: 'center' },
  pickerCloseBtnText: { color: '#8E8E93', fontSize: 14 },
  accordionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
  },
  accordionTitle: { fontSize: 13, fontWeight: '600', color: '#666' },
  sectionDividerText: { fontSize: 12, fontWeight: 'bold', color: '#8E8E93', marginTop: 8, marginBottom: 4 },

  // ゲスト追加用新規スタイル
  pickerToolbarRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  guestToggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: '#5856D6',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    height: 40,
  },
  guestToggleBtnText: { color: '#5856D6', fontSize: 12, fontWeight: '600' },
  guestInputRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10, gap: 8 },
  guestInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#5856D6',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
  },
  guestSubmitBtn: {
    backgroundColor: '#5856D6',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    height: 40,
    justifyContent: 'center',
  },
  guestSubmitBtnText: { color: '#FFF', fontSize: 14, fontWeight: 'bold' },

  selectedBadge: {
    backgroundColor: '#8E8E93',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginRight: 8,
  },
  selectedBadgeText: { color: '#FFF', fontSize: 10, fontWeight: 'bold' },
});

module.exports = { styles };
