'use strict';

/**
 * 設定画面の見た目の決まり。設定画面（SettingsScreen.js）と、そこから切り出した窓
 * （書き出し・問い合わせ・アカウントの削除など）で分け合う（2026-10-05 に SettingsScreen.js から移した）。
 */
const { StyleSheet } = require('./rn');
const { IS_WEB, SAFE_TOP_PADDING, WEB_TOP_PADDING } = require('./IS_WEB');
const { getShadowStyle } = require('./shadowStyle');

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F2F2F7', paddingTop: IS_WEB ? WEB_TOP_PADDING : SAFE_TOP_PADDING },
  container: { flex: 1 },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 10,
    color: '#1a1a1a',
  },
  section: { marginTop: 20, marginBottom: 10 },
  sectionTitle: {
    fontSize: 13,
    color: '#8E8E93',
    textTransform: 'uppercase',
    marginLeft: 32,
    marginBottom: 6,
  },
  sectionContainer: {
    backgroundColor: '#FFF',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: '#C6C6C8',
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginLeft: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#C6C6C8',
    backgroundColor: '#FFF',
  },
  hovered: { backgroundColor: '#F2F2F7' },
  itemLeft: { flexDirection: 'row', alignItems: 'center' },
  itemIcon: { width: 24, marginRight: 12 },
  itemText: { fontSize: 17, color: '#000' },
  iconContainer: { width: 32, height: 32, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  itemRight: { flexDirection: 'row', alignItems: 'center' },
  timestamp: { fontSize: 12, color: '#8E8E93' },
  // 団体ID/団体名は値が長く、狭い画面ではラベルと同じ行に収まらない。
  // 値をラベルの下へ回し、折り返しても見出しと衝突しないようにする
  itemStack: { flexDirection: 'column', alignItems: 'flex-start' },
  timestampStack: { marginTop: 4, marginLeft: 36 },
  footer: { marginTop: 30, marginBottom: 50, alignItems: 'center' },
  versionText: { fontSize: 14, color: '#8E8E93', marginBottom: 4 },
  statusText: { fontSize: 12, color: '#34C759' },
  // 目立たせないが、探して見つからないと困る。すぐ上の versionText と同じ濃さにする。
  // #C7C7CC だと明るいテーマで地との比が 1.5 しかなく、ほぼ見えなかった
  legalText: { fontSize: 11, color: '#8E8E93', marginTop: 10, textDecorationLine: 'underline' },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '85%',
    maxWidth: 350,
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 20,
    alignItems: 'center',
  },
  modalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 8 },
  modalMessage: { fontSize: 14, color: '#3C3C43', textAlign: 'center', marginBottom: 20 },
  modalButtons: { width: '100%', gap: 10 },
  modalButtonsRow: { flexDirection: 'row', width: '100%', gap: 10 },
  radioBtn: {
    flex: 1,
    paddingVertical: 8,
    backgroundColor: '#F2F2F7',
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 4,
  },
  radioBtnActive: { backgroundColor: '#007AFF' },
  radioBtnText: { fontSize: 13, color: '#8E8E93', fontWeight: 'bold' },
  radioBtnTextActive: { color: '#FFF' },
  ratioHintText: { fontSize: 11, color: '#8E8E93', marginTop: 6, paddingHorizontal: 4 },
  dateSelector: {
    flex: 1,
    backgroundColor: '#F2F2F7',
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
  },
  dateSelectorText: { fontSize: 14, color: '#000' },
  modalBtn: { paddingVertical: 12, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  modalBtnText: { fontSize: 16, fontWeight: 'bold' },
  monthNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    backgroundColor: '#F2F2F7',
    borderRadius: 8,
    paddingVertical: 4,
  },
  monthNavBtn: { padding: 8 },
  monthNavText: { fontSize: 14, fontWeight: 'bold', flex: 1, textAlign: 'center', color: '#000' },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F2F2F7',
    borderRadius: 8,
    height: 36,
    paddingLeft: 12,
  },
  stepperValue: { fontSize: 16, color: '#000', marginRight: 8 },
  stepperControls: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E5E5EA',
    borderRadius: 8,
    height: 32,
    marginRight: 2,
  },
  stepperBtn: { paddingHorizontal: 12, height: '100%', justifyContent: 'center', alignItems: 'center' },
  stepperDivider: { width: 1, height: 20, backgroundColor: '#C6C6C8' },
  filterGroup: { width: '100%', marginBottom: 16 },
  filterLabel: { fontSize: 12, color: '#8E8E93', marginBottom: 4, fontWeight: '600' },
  filterInput: {
    backgroundColor: '#F2F2F7',
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    color: '#000',
    borderWidth: 1,
    borderColor: '#E5E5EA',
  },
  flexRow: { flexDirection: 'row', alignItems: 'center' },
  supportButton: Object.assign(
    {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#FF2D55',
      marginHorizontal: 16,
      marginVertical: 8,
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 12,
    },
    getShadowStyle({
      shadowColor: '#FF2D55',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    })
  ),
  supportButtonHovered: { backgroundColor: '#E0284A', transform: [{ scale: 0.99 }] },
  supportButtonContent: { flexDirection: 'row', alignItems: 'center' },
  supportButtonText: { color: '#FFF', fontSize: 16, fontWeight: 'bold', marginLeft: 10 },
  tagChip: {
    backgroundColor: '#F2F2F7',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E5E5EA',
  },
  tagChipActive: { backgroundColor: '#007AFF', borderColor: '#007AFF' },
  tagChipText: { fontSize: 13, color: '#000' },
  suggestionsContainer: { flexDirection: 'row', marginTop: 8, paddingVertical: 4 },
  suggestionChip: {
    backgroundColor: '#E5E5EA',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 6,
  },
  suggestionText: { fontSize: 12, color: '#333' },
});

module.exports = { styles };
